# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_remove_plot_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
